---

apiVersion: builtin
kind: LabelTransformer
metadata:
  name: sealedSecretName

labels:
  app.kubernetes.io/name: rabbitmq

fieldSpecs:
  - path: metadata/labels
    create: true
  
  - kind: SealedSecret
    path: spec/template/metadata/labels
    create: true
